<StackLayout>:
    orientation: "lr-tb"
    spacing: 10
    padding: 10

    Button:
        text: "First"
        size_hint: None, .15
        width: 100
    Button:
        text: "Second"
        size_hint: None, .15
        width: 120
    Button:
        text: "Third"
        size_hint: None, .15
        width: 140

    Button:
        text: "Fourth"
        size_hint: None, .15
        width: 160

    Button:
        text: "Fourth"
        size_hint: None, .15
        width: 180

    Button:
        text: "Fourth"
        size_hint: None, .15
        width: 200

    Button:
        text: "Fourth"
        size_hint: None, .15
        width: 220

    Button:
        text: "Fourth"
        size_hint: None, .15
        width: 240

    Button:
        text: "Fourth"
        size_hint: None, .15
        width: 260
